= Spring Native with JHipster

This repository contains five apps we (https://github.com/joshlong[@joshlong] and https://github.com/mraible[@mraible]) used to figure out how to make Spring Native work with JHipster.

- `spring-native-webflux` - no client, no db, just WebFlux
- `spring-native-mvc` - no client, no db, just Spring MVC
- `angular-webflux` - Angular client, no db
- `postgres-webflux` - Angular, WebFlux, R2DBC + PostgreSQL
- `postgres-mvc` - Angular, Spring MVC, JPA + PostgreSQL

You should be able to create a JHipster monolith with OIDC, then make the following changes.

. Modify `pom.xml` to add native, adjust dependencies, and disable devtools:
+
[source,xml]
----
<repository>
    <id>spring-releases</id>
    <name>Spring Releases</name>
    <url>https://repo.spring.io/release</url>
    <snapshots>
        <enabled>false</enabled>
    </snapshots>
</repository>

<pluginRepository>
    <id>spring-releases</id>
    <name>Spring Releases</name>
    <url>https://repo.spring.io/release</url>
    <snapshots>
        <enabled>false</enabled>
    </snapshots>
</pluginRepository>
...

<repackage.classifier/>
<spring-native.version>0.11.0</spring-native.version>
...

<!-- If reactive, comment out boringssl. This allows Spring Native to build the image and gets around this error:
    Error: Classes that should be initialized at run time got initialized during image building:
    io.netty.buffer.UnpooledUnsafeDirectByteBuf the class was requested to be initialized at run time
    (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf).
    To see why io.netty.buffer.UnpooledUnsafeDirectByteB got initialized use
    trace-class-initialization=io.netty.buffer.UnpooledUnsafeDirectByteBuf
-->
<!--dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-tcnative-boringssl-static</artifactId>
</dependency-->

<dependency>
    <groupId>org.springframework.experimental</groupId>
    <artifactId>spring-native</artifactId>
    <version>${spring-native.version}</version>
</dependency>

<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <classifier>${repackage.classifier}</classifier>
        <image>
            <builder>paketobuildpacks/builder:tiny</builder>
            <env>
                <BP_NATIVE_IMAGE>true</BP_NATIVE_IMAGE>
            </env>
        </image>
    </configuration>
</plugin>
<plugin>
    <groupId>org.springframework.experimental</groupId>
    <artifactId>spring-aot-maven-plugin</artifactId>
    <version>${spring-native.version}</version>
    <executions>
        <execution>
            <id>test-generate</id>
            <goals>
                <goal>test-generate</goal>
            </goals>
        </execution>
        <execution>
            <id>generate</id>
            <goals>
                <goal>generate</goal>
            </goals>
        </execution>
    </executions>
</plugin>

<profile>
    <id>native</id>
    <properties>
        <repackage.classifier>exec</repackage.classifier>
        <native-buildtools.version>0.9.8</native-buildtools.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
                <version>${native-buildtools.version}</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <id>test-native</id>
                        <phase>test</phase>
                        <goals>
                            <goal>test</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>build-native</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</profile>
----

. If you're using Spring MVC, exclude Mockito from `spring-boot-starter-test`:
+
[source,xml]
----
<exclusion>
    <groupId>org.mockito</groupId>
    <artifactId>*</artifactId>
</exclusion>
----
+
And delete any tests that import Mockito. https://github.com/spring-projects-experimental/spring-native/issues/1343[Mockito isn't supported yet].
+
[source,shell]
----
rm src/test/java/com/mycompany/myapp/config/TestSecurityConfiguration.java
rm src/test/java/com/mycompany/myapp/web/rest/PostResourceIT.java
rm src/test/java/com/mycompany/myapp/config/WebConfigurerTest.java
rm src/test/java/com/mycompany/myapp/security/oauth2/CustomClaimConverterIT.java
rm src/test/java/com/mycompany/myapp/config/StaticResourcesWebConfigurerTest.java
rm src/test/java/com/mycompany/myapp/security/oauth2/AudienceValidatorTest.java
rm src/test/java/com/mycompany/myapp/IntegrationTest.java
rm src/test/java/com/mycompany/myapp/web/rest/PublicUserResourceIT.java
rm src/test/java/com/mycompany/myapp/config/timezone/HibernateTimeZoneIT.java
rm src/test/java/com/mycompany/myapp/web/rest/LogoutResourceIT.java
rm src/test/java/com/mycompany/myapp/web/rest/TagResourceIT.java
rm src/test/java/com/mycompany/myapp/web/rest/AccountResourceIT.java
rm src/test/java/com/mycompany/myapp/web/rest/errors/ExceptionTranslatorIT.java
rm src/test/java/com/mycompany/myapp/service/UserServiceIT.java
rm src/test/java/com/mycompany/myapp/web/rest/UserResourceIT.java
rm src/test/java/com/mycompany/myapp/web/rest/BlogResourceIT.java
----

. Delete `spring-logback.xml` and tone down logging
+
[source,yaml]
----
logging:
  level:
    root: ERROR
    io.netty: ERROR
    org.springframework: INFO
----

. If using Spring MVC, swap Undertow dependencies for Tomcat, modify `WebConfigurer` to comment out `setLocationForStaticAssets(server)`.

. Update main `App.java` to add hints for Micrometer and Spring Security
+
[source,java]
----
import org.springframework.nativex.hint.TypeHint;

@TypeHint(
    types = {
        org.HdrHistogram.Histogram.class,
        org.HdrHistogram.ConcurrentHistogram.class,
        org.springframework.security.oauth2.jwt.JwtDecoder.class
    })
----

. Add springdocs native dependency:
+
[source,xml]
----
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-native</artifactId>
    <version>1.6.0</version>
</dependency>
----

. Liquibase is https://github.com/spring-projects-experimental/spring-native/issues/620[not supported yet], but you can make it work by adding files from https://github.com/liquibase/liquibase/pull/2005[this pull request] to your `src/main/resources/META-INF/native-image/liquibase` directory.

. Add type hints for Liquibase and related classes.
+
[source,java]
----
@TypeHint(
    types = {
        ...
        liquibase.configuration.LiquibaseConfiguration.class,
        com.zaxxer.hikari.HikariDataSource.class,
        liquibase.change.core.LoadDataColumnConfig.class,
        tech.jhipster.domain.util.FixedPostgreSQL10Dialect.class,
        org.hibernate.type.TextType.class
    })
----

. If you're using JPA, https://docs.jboss.org/hibernate/orm/5.4/topical/html_single/bytecode/BytecodeEnhancement.html#_build_time_enhancement[configure Hibernate build-time bytecode enhancement]. Add the plugin right after the `spring-aot-maven-plugin`.
+
Then, add the following `@JdkProxyHint` to you main application class.
+
[source,java]
----
@JdkProxyHint(
    types = {
        org.springframework.data.jpa.repository.support.CrudMethodMetadata.class,
        org.springframework.aop.SpringProxy.class,
        org.springframework.aop.framework.Advised.class,
        org.springframework.core.DecoratingProxy.class
    })
----
+
And, add the following to the top of the `User` entity
+
[source,java]
----
@EntityListeners(AuditingEntityListener.class)
----

. If Spring WebFlux, remove `@Component` from `SpaWebFilter` (should be fixed in the next JHipster release)

. If using Spring WebFlux with R2DBC, we https://github.com/jhipster/generator-jhipster/pull/17277#issuecomment-993132173[haven't figured that one out yet].

. Build with  `./mvnw package -Pnative,prod -DskipTests`

== Known Issues

- https://github.com/spring-projects-experimental/spring-native/issues/1365[`Code should not be empty`] happens with Spring MVC. Removing Mockito and tests fixes it.
- Metrics don't work (`UnsupportedFeatureError: ThreadMXBean methods`)
- Logs don't work
- Configuration doesn't work
+
----
org.springframework.http.converter.HttpMessageNotWritableException: No converter for [class org.springframework.boot.actuate.context.properties.ConfigurationPropertiesReportEndpoint$ApplicationConfigurationProperties] with preset Content-Type 'null'
----
- H2 doesn't work
+
----
java.lang.IllegalStateException: Failed to process lifecycle methods on bean definition with name 'h2TCPServer'
----
+
It might be possible to fix with a `@TypeHint` for `org.h2.tools.Server.class`. However, this class is not in the classpath by default.
